### ISSUE TITLE
default for rookies / callups

### ISSUE THREAD

**Issue by evanhaldane** [campbellyamane/futureslate#1]
I'd imagine that rookies / callups peform significantly worse than league average in their first game. Unfortunately, the totals for that split is not easily findable using the Play Index or Fangraphs. One would have to dive into Retrosheet. In the meantime, something more pessimistic is probably more accurate.

**Comment by campbellyamane** [comment]
Good point. I've changed the defaults to a rookie average as opposed to a league-wide average
